@echo off
rem OpenClaw Gateway (v2026.2.22-2)
set "TMPDIR=C:\Users\ANUSHR~1\AppData\Local\Temp"
set "PATH=C:\Program Files\Python311\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\MinGW\bin;%%JAVA%%\bin;C:\ProgramData\chocolatey\bin;C:\sqlite3;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build;C:\Users\Anushree Jain\Anaconda;C:\Users\Anushree Jain\Anaconda\Scripts;C:\Program Files\Tesseract-OCR;C:\Program Files\MongoDB\Server\8.0\bin;C:\Users\Anushree Jain\AppData\Roaming\Python\Python311\Scripts\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Python311\;C:\Program Files\Python311\Scripts\;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\ffmpeg\bin;C:\Program Files\heroku\bin;C:\Program Files (x86)\HP\HP OCR\DB_Lib\;C:\Program Files\HP\Common\HPDestPlgIn\;C:\Program Files (x86)\HP\Common\HPDestPlgIn\;C:\Users\Anushree Jain\php-8.2.27-Win32-vs16-x64\;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Python312\;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Launcher\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Anushree Jain\AppData\Local\Programs\Python\Python311\;C:\Users\Anushree Jain\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2\bin;;C:\Users\Anushree Jain\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Anushree Jain\pycharm\PyCharm Community Edition 2024.1.2\bin;;C:\Users\Anushree Jain\Anaconda;C:\Users\Anushree Jain\Anaconda\Scripts;C:\Users\Anushree Jain\AppData\Local\Programs\mongosh\;C:\Program Files\CMake\bin;C:\Users\Anushree Jain\.dotnet\tools;C:\Program Files\HP\Common\HPDestPlgIn\;C:\Program Files (x86)\HP\Common\HPDestPlgIn\;C:\flutter_windows_3.35.3-stable\flutter\bin;C:\Android\Sdk\cmdline-tools\latest\bin;C:\Android\Sdk\platform-tools;C:\Users\Anushree Jain\AppData\Local\Pub\Cache\bin;C:\Users\Anushree Jain\AppData\Roaming\npm"
set "OPENCLAW_GATEWAY_PORT=18789"
set "OPENCLAW_GATEWAY_TOKEN=my-gateway-token-999"
set "OPENCLAW_SYSTEMD_UNIT=openclaw-gateway.service"
set "OPENCLAW_SERVICE_MARKER=openclaw"
set "OPENCLAW_SERVICE_KIND=gateway"
set "OPENCLAW_SERVICE_VERSION=2026.2.22-2"
"C:\Program Files\nodejs\node.exe" "C:\Users\Anushree Jain\AppData\Roaming\npm\node_modules\openclaw\dist\index.js" gateway --port 18789
